return {
  -- Copilot
  -- {
  --   "zbirenbaum/copilot.lua",
  --   cmd = "Copilot",
  --   event = "InsertEnter",
  --   config = function()
  --     require("copilot").setup({
  --       panel = {
  --         enabled = false,
  --       },
  --       suggestion = {
  --         enabled = false,
  --       },
  --       filetypes = {
  --         yaml = true,
  --         lua = true,
  --         javascript = true,
  --         typescript = true,
  --         javascriptreact = true,
  --         typescriptreact = true,
  --       },
  --     })
  --   end,
  -- },
  -- {
  --   "zbirenbaum/copilot-cmp",
  --   config = function()
  --     require("copilot_cmp").setup({})
  --   end,
  -- },
}
